# -*- coding: utf-8 -*-
"""Examen_Calidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6OHXkQArODsr-khf3-pOx9tv35I-aXn
"""

import streamlit as st
import pandas as pd
from datetime import datetime
import re

# Simulación de base de datos en memoria
if 'pacientes' not in st.session_state:
    st.session_state['pacientes'] = []
if 'citas' not in st.session_state:
    st.session_state['citas'] = []

st.set_page_config(page_title="SIGAV - Sistema de Citas", layout="centered")
st.title("🧠 SIGAV - Gestión de Atenciones Virtuales_Corregido")

# --- Registro de paciente
st.header("👤 Registro de Paciente")
with st.form("form_registro"):
    nombre = st.text_input("Nombre completo")
    dni = st.text_input("DNI")
    correo = st.text_input("Correo electrónico")
    registrar = st.form_submit_button("Registrar")

    if registrar:
        # Validación del nombre
        if not nombre.strip():
            st.error("El nombre no puede estar vacío.")
        elif not re.match("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$", nombre):
            st.error("El nombre no puede contener números ni caracteres especiales.")
        # Validación del DNI
        elif not dni.isdigit() or len(dni) != 8:
            st.error("El DNI debe contener exactamente 8 dígitos y solo números.")
        # Validación del correo
        elif "@" not in correo:
            st.error("El correo electrónico debe contener el carácter '@'.")
        else:
            # Si pasa las validaciones, registrar al paciente
            paciente = {"nombre": nombre, "dni": dni, "correo": correo}
            st.session_state.pacientes.append(paciente)
            st.success("Paciente registrado.")

st.subheader("📋 Pacientes registrados")
st.dataframe(pd.DataFrame(st.session_state.pacientes))

# --- Agendamiento de cita
st.header("📅 Agendar Cita")
with st.form("form_cita"):
    dni_cita = st.selectbox("Seleccionar DNI", [p["dni"] for p in st.session_state.pacientes])
    fecha = st.date_input("Fecha de cita")
    motivo = st.text_input("Motivo")
    profesional = st.selectbox("Profesional", ["Psic. Ana", "Psic. Luis"])
    agendar = st.form_submit_button("Agendar")

    if agendar:
        # Validación de fecha pasada
        if fecha < datetime.now().date():
            st.error("No se puede agendar una cita en una fecha pasada.")
        # Validación de cita duplicada en el mismo día
        elif any(cita["dni"] == dni_cita and cita["fecha"] == fecha.strftime("%Y-%m-%d") for cita in st.session_state.citas):
            st.error("Ya existe una cita programada para este paciente en la misma fecha.")
        else:
            # Si pasa las validaciones, agendar la cita
            cita = {
                "dni": dni_cita,
                "fecha": fecha.strftime("%Y-%m-%d"),
                "motivo": motivo,
                "profesional": profesional
            }
            st.session_state.citas.append(cita)
            st.success("Cita agendada.")

st.subheader("📑 Citas Programadas")
st.dataframe(pd.DataFrame(st.session_state.citas))


if st.button("🔄 Exportar citas a CSV"):
    if st.session_state.citas:
        # Crear un DataFrame con las citas
        citas_df = pd.DataFrame(st.session_state.citas)

        # Crear un archivo CSV en memoria
        csv_buffer = StringIO()
        citas_df.to_csv(csv_buffer, index=False)
        csv_data = csv_buffer.getvalue()

        # Agregar un botón de descarga
        st.download_button(
            label="📥 Descargar citas como CSV",
            data=csv_data,
            file_name="citas_exportadas.csv",
            mime="text/csv",
        )
    else:
        st.error("No hay citas programadas para exportar.")
