# -*- coding: utf-8 -*-
"""Examen_Calidad.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F6OHXkQArODsr-khf3-pOx9tv35I-aXn
"""

import streamlit as st
import pandas as pd
from datetime import datetime

# Simulación de base de datos en memoria
if 'pacientes' not in st.session_state:
    st.session_state['pacientes'] = []
if 'citas' not in st.session_state:
    st.session_state['citas'] = []

st.set_page_config(page_title="SIGAV - Sistema de Citas", layout="centered")
st.title("🧠 SIGAV - Gestión de Atenciones Virtuales")

# --- Registro de paciente
st.header("👤 Registro de Paciente")
with st.form("form_registro"):
    nombre = st.text_input("Nombre completo")
    dni = st.text_input("DNI")
    correo = st.text_input("Correo electrónico")
    registrar = st.form_submit_button("Registrar")

    if registrar:
        # ❌ Errores intencionales: sin validación de vacíos ni duplicados
        paciente = {"nombre": nombre, "dni": dni, "correo": correo}
        st.session_state.pacientes.append(paciente)
        st.success("Paciente registrado.")

st.subheader("📋 Pacientes registrados")
st.dataframe(pd.DataFrame(st.session_state.pacientes))

# --- Agendamiento de cita
st.header("📅 Agendar Cita")
with st.form("form_cita"):
    dni_cita = st.selectbox("Seleccionar DNI", [p["dni"] for p in st.session_state.pacientes])
    fecha = st.date_input("Fecha de cita")
    motivo = st.text_input("Motivo")
    profesional = st.selectbox("Profesional", ["Psic. Ana", "Psic. Luis"])
    agendar = st.form_submit_button("Agendar")

    if agendar:
        # ❌ No se valida si ya tiene cita ese día
        cita = {
            "dni": dni_cita,
            "fecha": fecha.strftime("%Y-%m-%d"),
            "motivo": motivo,
            "profesional": profesional
        }
        st.session_state.citas.append(cita)
        st.success("Cita agendada.")

st.subheader("📑 Citas Programadas")
st.dataframe(pd.DataFrame(st.session_state.citas))

# --- Exportar sin validación
if st.button("🔄 Exportar citas a CSV"):
    pd.DataFrame(st.session_state.citas).to_csv("citas_exportadas.csv", index=False)
    st.success("Citas exportadas como 'citas_exportadas.csv'")
